package interfaz;

public class Ver_Perfil__no_registrado_ {
	public Inicio_no_registrado_item _inicio_no_registrado;
	public Ver_me_gustas__no_registrado_ _ver_me_gustas__no_registrado_;
	public Vista_detalle__no_registrado_ _vista_detalle__no_registrado_;
	public Usuario__no_registrado__item _usuario__no_registrado_;
	public Comentario__no_registrado__item _comentario__no_registrado_;
	public Ver_perfil__usuario_no_registrado_ _ver_perfil_privado__usuario_no_registrado_;
	public Ver_perfil_publico__usuario_no_registrado_ _ver_perfil_publico__usuario_no_registrado_;
}